##Phase-2

##NumPy Basics  
##Task1-->Array, Shape of Array, Vectorization(Applying arithmetic operation on array),Broadcast(Applying operation either btw array or scalar value,array of different sizes)

In [12]:
import numpy as np
print("Task 1 Basics:)")
array=np.random.randint(low=1,high=50,size=(3,3))
print("Array of 3X3 Dimension: ",array)
square=array**2## Broadcasting
print("Square of Array: ",square)
row_wise_sum=np.sum(array,axis=1)## Vectorization
print("Row-wise Sum: ",row_wise_sum)
column_wise_sum=np.sum(array,axis=0)
print("Column-wise Sum: ",column_wise_sum)

Task 1 Basics:)
Array of 3X3 Dimension:  [[46 31 15]
 [48 27 27]
 [17 30 26]]
Square of Array:  [[2116  961  225]
 [2304  729  729]
 [ 289  900  676]]
Row-wise Sum:  [ 92 102  73]
Column-wise Sum:  [111  88  68]


Task 2-->>Pandas and its basics

In [ ]:
import numpy as np
import pandas as pd
##Series of Data
data=pd.Series([1,2,3],index=['a','b','c'])
print(data)
## DataFrame
data1={'Name':['Fajar','Saim','Muskan'],'ID':[1,2,3]}
data2={'City':['Lahore','Karachi','Gujranwala'],'ID':[1,2,4]}
data3={'ID':[1,2,1],'Age':[18,22,24]}
df1=pd.DataFrame(data1)
df2=pd.DataFrame(data2)
df3=pd.DataFrame(data3)
print(df1)
##Loc index wise inclusive
value=df1.loc[1]
print(value)
##iLoc position wise exclusive
value1=df1.iloc[2]
print(value1)
## Merging
merger=pd.merge(df1,df2,how='left')
print(merger)
## Groupby
group_by=df3.groupby('ID').sum()
print(group_by)
## Pivot Table
pivot=pd.pivot_table(df3,values='Age',index='ID',aggfunc='mean')
print(pivot)


a    1
b    2
c    3
dtype: int64
     Name  ID
0   Fajar   1
1    Saim   2
2  Muskan   3
Name    Saim
ID         2
Name: 1, dtype: object
Name    Muskan
ID           3
Name: 2, dtype: object
     Name  ID     City
0   Fajar   1   Lahore
1    Saim   2  Karachi
2  Muskan   3      NaN
    Age
ID     
1    42
2    22
     Age
ID      
1   21.0
2   22.0


## Load a csv and groupby average_score on gender

In [3]:
print("Group_by Score:)")
##data=pd.read_csv('data.csv')
##print(data)
##group_by=data.groupby('gender')['average_score'].mean()
##print(group_by)
import numpy as np
import pandas as pd
data=pd.DataFrame({'ID':[1,2,3,2,1],'Name':["Fajar","Saim","Muskan","Saim","Fajar"],'Score':[33,43,54,23,12],'Gender':["Female","Male","Female","Male","Female"]})
print(data)
group_by=data.groupby('Gender')['Score'].mean()
print(group_by)

Group_by Score:)
   ID    Name  Score  Gender
0   1   Fajar     33  Female
1   2    Saim     43    Male
2   3  Muskan     54  Female
3   2    Saim     23    Male
4   1   Fajar     12  Female
Gender
Female    33.0
Male      33.0
Name: Score, dtype: float64


##Cleaning Data

In [8]:
import pandas as pd
import numpy as np
data = {
    'Name': ['Fajar', 'Saim', 'Ahsan', 'Muskan', 'Hijab'],
    'Gender': ['Female', 'Male', 'Male', np.nan, 'Female'],
    'Age': [25, 30, np.nan, 22, np.nan],
    'Score': [85, np.nan, 78, 90, 88]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)
##Drop values
drop_value=df.dropna()
print("DataFrame after removing missing values:\n",drop_value)
##Fill values
fill_value=df.fillna(0)
print("DataFrame after filling missing values:\n",fill_value)
##Is empty-->Return bool values
null_value=df.isnull()
print("DataFrame after checking for missing values:\n",null_value)
## Is empty-->Sum of null
sum_of_null_value=df.isnull().sum()
print("DataFrame after checking for missing values:\n",sum_of_null_value)


Original DataFrame:
      Name  Gender   Age  Score
0   Fajar  Female  25.0   85.0
1    Saim    Male  30.0    NaN
2   Ahsan    Male   NaN   78.0
3  Muskan     NaN  22.0   90.0
4   Hijab  Female   NaN   88.0
DataFrame after removing missing values:
     Name  Gender   Age  Score
0  Fajar  Female  25.0   85.0
DataFrame after filling missing values:
      Name  Gender   Age  Score
0   Fajar  Female  25.0   85.0
1    Saim    Male  30.0    0.0
2   Ahsan    Male   0.0   78.0
3  Muskan       0  22.0   90.0
4   Hijab  Female   0.0   88.0
DataFrame after checking for missing values:
     Name  Gender    Age  Score
0  False   False  False  False
1  False   False  False   True
2  False   False   True  False
3  False    True  False  False
4  False   False   True  False
DataFrame after checking for missing values:
 Name      0
Gender    1
Age       2
Score     1
dtype: int64


##Load a CSV file and fill missing numeric values with the column mean.

In [4]:
import pandas as pd
import numpy as np
data = {
    'Name': ['Fajar', 'Saim', 'Ahsan', 'Muskan', 'Hijab'],
    'Gender': ['Female', 'Male', 'Male', np.nan, 'Female'],
    'Age': [25, 30, np.nan, 22, np.nan],
    'Score': [85, np.nan, 78, 90, 88]
}
values=pd.DataFrame(data)
print("Original DataFrame:\n",values)
mean_value=values['Score'].mean()
values['Score'].fillna(mean_value)
print("New DataFrame:\n",values)

Original DataFrame:
      Name  Gender   Age  Score
0   Fajar  Female  25.0   85.0
1    Saim    Male  30.0    NaN
2   Ahsan    Male   NaN   78.0
3  Muskan     NaN  22.0   90.0
4   Hijab  Female   NaN   88.0
New DataFrame:
      Name  Gender   Age  Score
0   Fajar  Female  25.0   85.0
1    Saim    Male  30.0    NaN
2   Ahsan    Male   NaN   78.0
3  Muskan     NaN  22.0   90.0
4   Hijab  Female   NaN   88.0


##Type Converstions

In [13]:
import numpy as np
import pandas as pd
data={'ID':[1,2,1],'Age':["18","22","24"]}
df=pd.DataFrame(data)
print("Original DataFrame:\n",df)
print("Type of Age: ",type(df.loc[0,'Age']))
df['Age']=df['Age'].astype(int)
print("New DataFrame after changing age type:\n",df)
print("Type of Age: ",type(df.loc[0,'Age']))

Original DataFrame:
    ID Age
0   1  18
1   2  22
2   1  24
Type of Age:  <class 'str'>
New DataFrame after changing age type:
    ID  Age
0   1   18
1   2   22
2   1   24
Type of Age:  <class 'numpy.int64'>


##Filtering,Sorting,Slicing

In [17]:
import numpy as np
import pandas as pd
data = {
    'Name': ['Fajar', 'Saim', 'Ahsan', 'Muskan', 'Hijab', 'Munees', 'Sherri', 'Mustafa'],
    'Score': [99, 88, 91, 95, 84, 73, 96, 92]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n",df)
filtered_data=df[df['Score']>90]
print("Filtered DataFrame:\n",filtered_data)
sorted_data=df.sort_values(by='Score',ascending=False)
print("Sorted DataFrame:\n",sorted_data)
sliced_data=df.iloc[0:5]
print("Sliced DataFrame:\n",sliced_data)
top_five=df.nlargest(5,'Score')
print("Top Five DataFrame:\n",top_five)
top=df.head(5)
print("Top DataFrame:\n",top)
bottom=df.tail(5)
print("Bottom DataFrame:\n",bottom)

Original DataFrame:
       Name  Score
0    Fajar     99
1     Saim     88
2    Ahsan     91
3   Muskan     95
4    Hijab     84
5   Munees     73
6   Sherri     96
7  Mustafa     92
Filtered DataFrame:
       Name  Score
0    Fajar     99
2    Ahsan     91
3   Muskan     95
6   Sherri     96
7  Mustafa     92
Sorted DataFrame:
       Name  Score
0    Fajar     99
6   Sherri     96
3   Muskan     95
7  Mustafa     92
2    Ahsan     91
1     Saim     88
4    Hijab     84
5   Munees     73
Sliced DataFrame:
      Name  Score
0   Fajar     99
1    Saim     88
2   Ahsan     91
3  Muskan     95
4   Hijab     84
Top Five DataFrame:
       Name  Score
0    Fajar     99
6   Sherri     96
3   Muskan     95
7  Mustafa     92
2    Ahsan     91
Top DataFrame:
      Name  Score
0   Fajar     99
1    Saim     88
2   Ahsan     91
3  Muskan     95
4   Hijab     84
Bottom DataFrame:
       Name  Score
3   Muskan     95
4    Hijab     84
5   Munees     73
6   Sherri     96
7  Mustafa     92


##Date/Time Processing

In [19]:
import numpy as np
import pandas as pd
data = {
    'event': ['Exam', 'Meeting', 'Holiday', 'Workshop'],
    'date': ['2025-01-15', '2025-02-10', '2025-03-25', '2025-04-18']
}
df = pd.DataFrame(data)
print("Original DataFrame:\n",df)
df['date']=pd.to_datetime(df['date'])
print("New DataFrame:\n",df)
df['year']=df['date'].dt.year
df['month']=df['date'].dt.month
df['day']=df['date'].dt.day
print("New DataFrame:\n",df)

Original DataFrame:
       event        date
0      Exam  2025-01-15
1   Meeting  2025-02-10
2   Holiday  2025-03-25
3  Workshop  2025-04-18
New DataFrame:
       event       date
0      Exam 2025-01-15
1   Meeting 2025-02-10
2   Holiday 2025-03-25
3  Workshop 2025-04-18
New DataFrame:
       event       date  year  month  day
0      Exam 2025-01-15  2025      1   15
1   Meeting 2025-02-10  2025      2   10
2   Holiday 2025-03-25  2025      3   25
3  Workshop 2025-04-18  2025      4   18


##Outliner Detection

In [25]:
import pandas as pd
import numpy as np
data = {
    'Name': ['Fajar', 'Saim', 'Muskan', 'Hijab', 'Ahsan', 'Sumaira'],
    'Score': [85, 88, 90, 87, 86, 999]
}
df = pd.DataFrame(data)
q1 = df['Score'].quantile(0.25)
q3 = df['Score'].quantile(0.75)
iqr = q3 - q1

filtered_df = df[(df['Score'] >= q1 - 1.5 * iqr) & (df['Score'] <= q3 + 1.5 * iqr)]
print("Original Data:\n", df)
print("\nFiltered Data (without outliers):\n", filtered_df)


Original Data:
       Name  Score
0    Fajar     85
1     Saim     88
2   Muskan     90
3    Hijab     87
4    Ahsan     86
5  Sumaira    999

Filtered Data (without outliers):
      Name  Score
0   Fajar     85
1    Saim     88
2  Muskan     90
3   Hijab     87
4   Ahsan     86


##String Processing with Regex

In [24]:
import numpy as np
import pandas as pd
data = {
    'Name': ['Fajar123', 'Mus!Kan', 'S@aim_99', 'Ahsan#_1', 'Hija*_22b']
}
df = pd.DataFrame(data)
print("Original DataFrame:\n",df)
df['Name']=df['Name'].str.replace(r'[^a-zA-Z\s]','',regex=True)
print("New DataFrame:\n",df)

Original DataFrame:
         Name
0   Fajar123
1    Mus!Kan
2   S@aim_99
3   Ahsan#_1
4  Hija*_22b
New DataFrame:
      Name
0   Fajar
1  MusKan
2    Saim
3   Ahsan
4   Hijab
